Distinguish between test passed and test skipped

diff --git a/test/lib_test_functions b/test/lib_test_functions
--- a/test/lib_test_functions
+++ b/test/lib_test_functions
@@ -2,12 +2,19 @@
 # Incorporate into test scripts with  . $TESTDIR/lib_test_functions
 # vim: ft=sh
 
+# exit code for the test script
+EXIT_TEST_PASSED=0
+EXIT_TEST_FAILED=1
+EXIT_TEST_SKIPPED=2
+
+# utility functions
+
 check_exit_code() {
   ACTUAL=$1
   EXPECTED=$2
   if [ "$EXPECTED" -ne "$ACTUAL" ]; then
     echo Expected exit code $EXPECTED, got $ACTUAL >> $LOGFILE
-    exit 1
+    exit $EXIT_TEST_FAILED
   fi
   return 0
 }
@@ -19,7 +26,7 @@ check_file_is_empty() {
   if [ -n "$(cat $FILENAME)" ]; then
     echo "Got unexpected output on $TEXT_SOURCE" >> $LOGFILE
     copy_file_to_log "$FILENAME" "$TEXT_SOURCE"
-    exit 1
+    exit $EXIT_TEST_FAILED
   fi
 }
 
@@ -29,7 +36,7 @@ check_file_is_not_empty() {
   TEXT_SOURCE=$2  # a human-readable description of where the file content came from (e.g. "stdout" or "stderr")
   if [ -z "$(cat $FILENAME)" ]; then
     echo "Expected output on $TEXT_SOURCE but got nothing" >> $LOGFILE
-    exit 1
+    exit $EXIT_TEST_FAILED
   fi
 }
 
@@ -44,7 +51,7 @@ check_files_are_equal() {
     echo "Files $F1 and F2 differ" >> $LOGFILE
     copy_file_to_log $F1 "file 1"
     copy_file_to_log $F2 "file 2"
-    exit 1
+    exit $EXIT_TEST_FAILED
   fi
 }
 
